### PR TITLE
Minor typos :)

### PR DESCRIPTION
**Pull request by abhi18av**

### CODE REVIEW

**Comment by abhi18av** [comment]
Hi @guenchi , thanks for the merge 👍 

I'm really looking forward to learning and contributing to the `ChezScheme` ecosystem!

**Comment by guenchi** [comment]
> Hi @guenchi , thanks for the merge 👍
> 
> I'm really looking forward to learning and contributing to the `ChezScheme` ecosystem!

Hi thinks forward,

there are something to do (a lot of :) )

1.  https://github.com/guenchi/Igropyr

need more test, and I looking for rewrite it, maybe with https://github.com/becls/swish


2. package https://github.com/becls/swish with Raven eco-system

3. ffi-binding works:

https://github.com/guenchi/NumPy

https://github.com/guenchi/SciPy

https://github.com/guenchi/SymPy

https://github.com/guenchi/Matplotlib

https://github.com/guenchi/Pandas 

4.  https://github.com/guenchi/json

need more test

**Comment by abhi18av** [comment]
Hi @guenchi , thanks for the quick response!

I think the best way for me to move forward is to begin with tests and on closer look, I found https://github.com/ktakashi/chez-testing as the testing framework.

Is it good in your opinion? Otherwise please let me know of good examples of testing in `Chez Scheme` and I'd contribute to all the projects mentioned above :)

**Comment by guenchi** [comment]
> Hi @guenchi , thanks for the quick response!
> 
> I think the best way for me to move forward is to begin with tests and on closer look, I found https://github.com/ktakashi/chez-testing as the testing framework.
> 
> Is it good in your opinion? Otherwise please let me know of good examples of testing in `Chez Scheme` and I'd contribute to all the projects mentioned above :)

Thank you for the framework provided, knowing this is useful.

But my test here means stress testing in a high concurrency environment.

**Pull request merged**
